module.exports = `{"source_language": "en", "word": "brain", "character_grid": [["\u00fa", "k", "\u00fc", "b", "\u00ed", "n", "z", "d", "o"], ["u", "\u00e1", "n", "g", "e", "y", "z", "o", "\u00f1"], ["o", "\u00e9", "\u00fa", "\u00e1", "v", "e", "x", "u", "c"], ["c", "w", "d", "z", "t", "k", "m", "l", "e"], ["u", "b", "o", "w", "\u00ed", "a", "u", "q", "r"], ["g", "s", "m", "e", "c", "n", "k", "\u00fa", "e"], ["a", "o", "v", "t", "p", "\u00fa", "\u00e9", "k", "b"], ["f", "j", "i", "j", "l", "i", "b", "\u00f3", "r"], ["s", "q", "l", "j", "j", "f", "q", "g", "o"]], "word_locations": {"8,2,8,3,8,4,8,5,8,6,8,7,8,8": "cerebro"}, "target_language": "es"}
{"source_language": "en", "word": "girl", "character_grid": [["o", "s", "\u00f3", "x", "h", "\u00f1", "h"], ["\u00fc", "r", "g", "o", "l", "\u00fa", "b"], ["a", "t", "c", "h", "i", "c", "a"], ["u", "\u00fa", "r", "w", "\u00e1", "t", "\u00e9"], ["p", "n", "v", "r", "q", "m", "l"], ["f", "d", "t", "e", "a", "\u00f3", "l"], ["u", "t", "n", "i", "\u00f1", "a", "s"]], "word_locations": {"2,2,3,2,4,2,5,2,6,2": "chica", "2,6,3,6,4,6,5,6": "ni\u00f1a"}, "target_language": "es"}
{"source_language": "en", "word": "boy", "character_grid": [["x", "c", "e", "x", "c", "i", "o"], ["e", "z", "q", "r", "h", "w", "y"], ["\u00f1", "\u00e9", "\u00f1", "w", "i", "n", "\u00e1"], ["o", "l", "a", "\u00e1", "c", "i", "n"], ["r", "v", "\u00f1", "s", "o", "\u00f1", "w"], ["k", "m", "w", "a", "\u00fc", "o", "w"], ["\u00f3", "r", "\u00fa", "b", "l", "g", "\u00fa"]], "word_locations": {"5,2,5,3,5,4,5,5": "ni\u00f1o", "4,0,4,1,4,2,4,3,4,4": "chico"}, "target_language": "es"}
{"source_language": "en", "word": "queen", "character_grid": [["v", "\u00e1", "q", "t", "b", "f", "q"], ["y", "x", "i", "a", "\u00fc", "v", "a"], ["r", "d", "y", "\u00ed", "t", "n", "a"], ["f", "v", "\u00f3", "w", "l", "a", "v"], ["b", "u", "\u00fa", "j", "q", "h", "\u00e1"], ["c", "o", "r", "e", "i", "n", "a"], ["h", "o", "d", "\u00fa", "w", "d", "\u00fc"]], "word_locations": {"2,5,3,5,4,5,5,5,6,5": "reina"}, "target_language": "es"}
{"source_language": "en", "word": "king", "character_grid": [["d", "c", "e", "h", "p"], ["f", "e", "\u00fc", "p", "t"], ["r", "s", "\u00f3", "\u00ed", "l"], ["e", "s", "\u00ed", "\u00f1", "a"], ["y", "g", "i", "o", "n"]], "word_locations": {"0,2,0,3,0,4": "rey"}, "target_language": "es"}
{"source_language": "en", "word": "clown", "character_grid": [["i", "q", "\u00ed", "l", "n", "n", "m", "\u00f3"], ["f", "t", "v", "\u00f1", "b", "m", "p", "a"], ["h", "j", "\u00e9", "t", "e", "t", "a", "z"], ["x", "\u00e1", "o", "i", "e", "\u00f1", "y", "\u00e9"], ["q", "\u00e9", "i", "\u00f3", "q", "s", "a", "s"], ["c", "u", "m", "y", "v", "l", "s", "x"], ["\u00fc", "\u00ed", "\u00f3", "m", "o", "t", "o", "k"], ["a", "g", "r", "n", "n", "\u00f3", "s", "m"]], "word_locations": {"6,1,6,2,6,3,6,4,6,5,6,6": "payaso"}, "target_language": "es"}
{"source_language": "en", "word": "clothes", "character_grid": [["z", "n", "w", "f", "m", "\u00e9"], ["d", "\u00f3", "q", "w", "n", "r"], ["z", "\u00e1", "v", "e", "\u00f3", "o"], ["r", "c", "z", "z", "m", "p"], ["\u00fc", "m", "\u00e1", "\u00fc", "n", "a"], ["e", "a", "e", "x", "\u00f1", "h"]], "word_locations": {"5,1,5,2,5,3,5,4": "ropa"}, "target_language": "es"}
{"source_language": "en", "word": "pineapple", "character_grid": [["i", "a", "p", "j", "r", "w"], ["k", "b", "n", "i", "u", "v"], ["v", "x", "z", "f", "ñ", "a"], ["u", "l", "o", "p", "e", "a"], ["l", "\u00fa", "\u00e9", "q", "j", "e"], ["a", "h", "ñ", "l", "k", "w"]], "word_locations": {"2,0,3,1,4,2,5,3": "piña"}, "target_language": "es"}
{"source_language": "en", "word": "bear", "character_grid": [["\u00fc", "\u00e1", "o", "s", "o"], ["k", "a", "k", "m", "l"], ["a", "x", "q", "e", "h"], ["p", "s", "a", "j", "\u00ed"], ["\u00e1", "q", "l", "j", "l"]], "word_locations": {"2,0,3,0,4,0": "oso"}, "target_language": "es"}`
